### ISSUE TITLE
Bug: chat apikey set failed, but `spring.ai.dashscope.apikey` success

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-ai-alibaba#23]
The cause of the problem is: During the automatic injection of the chat, the Embedding Model performs automatic injection. Therefore, the apikey setting fails. Because at this time, there is neither a good apikey nor an embedding apikey.

```java
static int count  = 0;

private static @NotNull DashScopeAutoConfiguration.ResolvedConnectionProperties resolveConnectionProperties(
	DashScopeParentProperties commonProperties, DashScopeParentProperties modelProperties, String modelType) {

StackTraceElement[] stackTrace = Thread.currentThread().getStackTrace();
count ++;
System.out.println("调用次数：" + count);
System.out.println("方法 resolveConnectionProperties 被调用，调用者是：");
for (StackTraceElement element : stackTrace) {
	
	if (element.getMethodName().equals("resolveConnectionProperties")) {
		
		System.out.println("  " + element.getClassName() + "." + element.getMethodName() + "() 由以下方法调用：");
		for (StackTraceElement caller : stackTrace) {
			if (!caller.getMethodName().equals("resolveConnectionProperties")) {
				System.out.println("    " + caller.getClassName() + "." + caller.getMethodName());
			}
		}
		break;
	}
}

String baseUrl = StringUtils.hasText(modelProperties.getBaseUrl()) ? modelProperties.getBaseUrl()
		: commonProperties.getBaseUrl();
String apiKey = StringUtils.hasText(modelProperties.getApiKey()) ? modelProperties.getApiKey()
		: commonProperties.getApiKey();
String workspaceId = StringUtils.hasText(modelProperties.getWorkspaceId()) ? modelProperties.getWorkspaceId()
		: commonProperties.getWorkspaceId();

Map<String, List<String>> connectionHeaders = new HashMap<>();
if (StringUtils.hasText(workspaceId)) {
	connectionHeaders.put("DashScope-Workspace", List.of(workspaceId));
}

Assert.hasText(baseUrl,
		"DashScope base URL must be set.  Use the connection property: spring.ai.dashscope.base-url or spring.ai.dashscope."
				+ modelType + ".base-url property.");
Assert.hasText(apiKey,
		"DashScope API key must be set. Use the connection property: spring.ai.dashscope.api-key or spring.ai.dashscope."
				+ modelType + ".api-key property.");

return new DashScopeAutoConfiguration.ResolvedConnectionProperties(baseUrl, apiKey, workspaceId,
		CollectionUtils.toMultiValueMap(connectionHeaders));
}
```

Replace the last method of DashScopeAutoConfiguration with this to see the cause of the problem

**Comment by chickenlj** [comment]
I reproduced this issue with the following configuration:

```yaml
spring:
  ai:
    dashscope:
      chat:
        api-key: ${AI_DASHSCOPE_API_KEY}
```

Here's the exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dashscopeEmbeddingModel' defined in class path resource [com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.class]: Failed to instantiate [com.alibaba.cloud.ai.dashscope.embedding.DashScopeEmbeddingModel]: Factory method 'dashscopeEmbeddingModel' threw exception with message: DashScope API key must be set. Use the connection property: spring.ai.dashscope.api-key or spring.ai.dashscope.embedding.api-key property.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.12.jar:6.1.12]
```

**Comment by chickenlj** [comment]
fixed with https://github.com/alibaba/spring-ai-alibaba/pull/26
