### ISSUE TITLE
bug: Dashscope voice transcription test failed

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-ai-alibaba#295]
## resources

![image](https://github.com/user-attachments/assets/f0a35d25-043f-4b4f-a18c-54edee6c6bf0)

## code 

```text
DashScopeAudioTranscriptionModel transcriptionModel = context.getBean(DashScopeAudioTranscriptionModel.class);
Resource audioFile = new ClassPathResource("/speech/jfk.flac");
System.out.println(audioFile);
String response = transcriptionModel.call(new AudioTranscriptionPrompt(audioFile)).getResult().getOutput();
System.out.println(response);
assertThat(response).isNotEmpty();
logger.info("Response: " + response);
```

## logs

```text

com.alibaba.cloud.ai.dashscope.common.DashScopeException: get transcription outcome failed

	at com.alibaba.cloud.ai.dashscope.api.DashScopeAudioTranscriptionApi.getOutcome(DashScopeAudioTranscriptionApi.java:136)
	at com.alibaba.cloud.ai.dashscope.audio.DashScopeAudioTranscriptionModel.toResponse(DashScopeAudioTranscriptionModel.java:236)
	at com.alibaba.cloud.ai.dashscope.audio.DashScopeAudioTranscriptionModel.call(DashScopeAudioTranscriptionModel.java:132)
	at com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeAutoConfigurationIT.lambda$transcribe$1(DashScopeAutoConfigurationIT.java:83)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.accept(AbstractApplicationContextRunner.java:434)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.consumeAssertableContext(AbstractApplicationContextRunner.java:363)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$0(AbstractApplicationContextRunner.java:341)
	at org.springframework.boot.test.util.TestPropertyValues.lambda$applyToSystemProperties$1(TestPropertyValues.java:174)
	at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:188)
	at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:173)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$1(AbstractApplicationContextRunner.java:341)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.withContextClassLoader(AbstractApplicationContextRunner.java:369)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.run(AbstractApplicationContextRunner.java:340)
	at com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeAutoConfigurationIT.transcribe(DashScopeAutoConfigurationIT.java:79)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at java.base/java.net.URI$Parser.parse(URI.java:3165)
	at java.base/java.net.URI.<init>(URI.java:623)
	at com.alibaba.cloud.ai.dashscope.api.DashScopeAudioTranscriptionApi.getOutcome(DashScopeAudioTranscriptionApi.java:130)
	... 16 more
```

![image](https://github.com/user-attachments/assets/20706abd-79f9-420b-874b-b9c34f8a6a3e)

**Comment by yuluo-yx** [comment]
@kevinlin09 can you take a look it. cc @chickenlj

**Comment by lx4556332** [comment]
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at java.base/java.net.URI$Parser.parse(URI.java:3165)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	at com.alibaba.cloud.ai.dashscope.api.DashScopeAudioTranscriptionApi.getOutcome(DashScopeAudioTranscriptionApi.java:183)
	... 127 common frames omitted
18:12:32.503 [http-nio-18080-exec-1] WARN  o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - [logException,254] - Resolved [com.alibaba.cloud.ai.dashscope.common.DashScopeException: get transcription outcome failed]

        String testFilePath = "http://localhost:8016/moxi.mp3";
        AudioTranscriptionResponse response = transcriptionModel.call(
                new AudioTranscriptionPrompt(
                        new UrlResource(testFilePath),
                        DashScopeAudioTranscriptionOptions.builder()
                                .model("fun-asr")
                                .build()
                )
        );
        return response.getResult().getOutput();

**Comment by lx4556332** [comment]
我也遇到这个问题哦
