### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by qiqi5526** [alibaba/spring-ai-alibaba#72]
I got a AbstractMethodError when I call DashScope Chat Model for getting keyword of a document

the code like below 

` public static void main(String[] args) {

        DashScopeApi dashScopeApi = new DashScopeApi("7777777777");
        DashScopeChatOptions options = DashScopeChatOptions.builder()
                .withModel("qwen2-vl-7b-instruct")
                .withTemperature(0.7f)
                .build();
        DashScopeChatModel chatModel = new DashScopeChatModel(dashScopeApi,options);// initialize your chat model
        KeywordMetadataEnricher enricher = new KeywordMetadataEnricher(chatModel, 5);

        Document doc = new Document("This is a document about artificial intelligence and its applications in modern technology.");

        List<Document> enrichedDocs = enricher.apply(List.of(doc));

        Document enrichedDoc = enrichedDocs.get(0);
        String keywords = (String) enrichedDoc.getMetadata().get("excerpt_keywords");
        System.out.println("Extracted keywords: " + keywords);
    }`

the exception as:

/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=55583:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/lrq/Downloads/ai-test/target/classes:/Users/lrq/.m2/repository/com/alibaba/cloud/ai/spring-ai-alibaba-starter/1.0.0-M2.1/spring-ai-alibaba-starter-1.0.0-M2.1.jar:/Users/lrq/.m2/repository/org/springframework/boot/spring-boot-starter/3.3.3/spring-boot-starter-3.3.3.jar:/Users/lrq/.m2/repository/org/springframework/boot/spring-boot/3.3.3/spring-boot-3.3.3.jar:/Users/lrq/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.3.3/spring-boot-autoconfigure-3.3.3.jar:/Users/lrq/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.3.3/spring-boot-starter-logging-3.3.3.jar:/Users/lrq/.m2/repository/ch/qos/logback/logback-classic/1.5.7/logback-classic-1.5.7.jar:/Users/lrq/.m2/repository/ch/qos/logback/logback-core/1.5.7/logback-core-1.5.7.jar:/Users/lrq/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.23.1/log4j-to-slf4j-2.23.1.jar:/Users/lrq/.m2/repository/org/apache/logging/log4j/log4j-api/2.23.1/log4j-api-2.23.1.jar:/Users/lrq/.m2/repository/org/slf4j/jul-to-slf4j/2.0.16/jul-to-slf4j-2.0.16.jar:/Users/lrq/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/Users/lrq/.m2/repository/org/springframework/spring-core/6.1.12/spring-core-6.1.12.jar:/Users/lrq/.m2/repository/org/springframework/spring-jcl/6.1.12/spring-jcl-6.1.12.jar:/Users/lrq/.m2/repository/org/yaml/snakeyaml/2.2/snakeyaml-2.2.jar:/Users/lrq/.m2/repository/com/alibaba/cloud/ai/spring-ai-alibaba-core/1.0.0-M2.1/spring-ai-alibaba-core-1.0.0-M2.1.jar:/Users/lrq/.m2/repository/com/alibaba/dashscope-sdk-java/2.15.1/dashscope-sdk-java-2.15.1.jar:/Users/lrq/.m2/repository/io/reactivex/rxjava2/rxjava/2.2.21/rxjava-2.2.21.jar:/Users/lrq/.m2/repository/org/projectlombok/lombok/1.18.26/lombok-1.18.26.jar:/Users/lrq/.m2/repository/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar:/Users/lrq/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.8.21/kotlin-stdlib-jdk8-1.8.21.jar:/Users/lrq/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.8.21/kotlin-stdlib-1.8.21.jar:/Users/lrq/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.8.21/kotlin-stdlib-common-1.8.21.jar:/Users/lrq/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/Users/lrq/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.8.21/kotlin-stdlib-jdk7-1.8.21.jar:/Users/lrq/.m2/repository/com/squareup/okio/okio/3.6.0/okio-3.6.0.jar:/Users/lrq/.m2/repository/com/squareup/okio/okio-jvm/3.6.0/okio-jvm-3.6.0.jar:/Users/lrq/.m2/repository/com/squareup/okhttp3/logging-interceptor/4.12.0/logging-interceptor-4.12.0.jar:/Users/lrq/.m2/repository/com/squareup/okhttp3/okhttp-sse/4.12.0/okhttp-sse-4.12.0.jar:/Users/lrq/.m2/repository/org/springframework/ai/spring-ai-retry/1.0.0-M2/spring-ai-retry-1.0.0-M2.jar:/Users/lrq/.m2/repository/org/springframework/retry/spring-retry/2.0.5/spring-retry-2.0.5.jar:/Users/lrq/.m2/repository/org/springframework/spring-webflux/6.1.12/spring-webflux-6.1.12.jar:/Users/lrq/.m2/repository/org/springframework/ai/spring-ai-spring-boot-autoconfigure/1.0.0-M2/spring-ai-spring-boot-autoconfigure-1.0.0-M2.jar:/Users/lrq/.m2/repository/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.jar:/Users/lrq/.m2/repository/com/squareup/okhttp3/okhttp/4.12.0/okhttp-4.12.0.jar:/Users/lrq/.m2/repository/org/springframework/ai/spring-ai-pdf-document-reader/1.0.0-M3/spring-ai-pdf-document-reader-1.0.0-M3.jar:/Users/lrq/.m2/repository/org/springframework/ai/spring-ai-core/1.0.0-M3/spring-ai-core-1.0.0-M3.jar:/Users/lrq/.m2/repository/io/swagger/core/v3/swagger-annotations/2.2.20/swagger-annotations-2.2.20.jar:/Users/lrq/.m2/repository/com/github/victools/jsonschema-module-swagger-2/4.35.0/jsonschema-module-swagger-2-4.35.0.jar:/Users/lrq/.m2/repository/org/springframework/cloud/spring-cloud-function-context/4.1.3/spring-cloud-function-context-4.1.3.jar:/Users/lrq/.m2/repository/net/jodah/typetools/0.6.2/typetools-0.6.2.jar:/Users/lrq/.m2/repository/org/springframework/cloud/spring-cloud-function-core/4.1.3/spring-cloud-function-core-4.1.3.jar:/Users/lrq/.m2/repository/org/json/json/20240303/json-20240303.jar:/Users/lrq/.m2/repository/org/antlr/ST4/4.3.4/ST4-4.3.4.jar:/Users/lrq/.m2/repository/org/antlr/antlr-runtime/3.5.3/antlr-runtime-3.5.3.jar:/Users/lrq/.m2/repository/org/antlr/antlr4-runtime/4.13.1/antlr4-runtime-4.13.1.jar:/Users/lrq/.m2/repository/io/projectreactor/reactor-core/3.6.10/reactor-core-3.6.10.jar:/Users/lrq/.m2/repository/org/reactivestreams/reactive-streams/1.0.4/reactive-streams-1.0.4.jar:/Users/lrq/.m2/repository/org/springframework/spring-context/6.1.13/spring-context-6.1.13.jar:/Users/lrq/.m2/repository/org/springframework/spring-aop/6.1.13/spring-aop-6.1.13.jar:/Users/lrq/.m2/repository/org/springframework/spring-beans/6.1.13/spring-beans-6.1.13.jar:/Users/lrq/.m2/repository/org/springframework/spring-expression/6.1.13/spring-expression-6.1.13.jar:/Users/lrq/.m2/repository/io/micrometer/micrometer-observation/1.12.10/micrometer-observation-1.12.10.jar:/Users/lrq/.m2/repository/org/springframework/spring-messaging/6.1.13/spring-messaging-6.1.13.jar:/Users/lrq/.m2/repository/org/springframework/spring-web/6.1.13/spring-web-6.1.13.jar:/Users/lrq/.m2/repository/io/micrometer/micrometer-core/1.13.4/micrometer-core-1.13.4.jar:/Users/lrq/.m2/repository/io/micrometer/micrometer-commons/1.13.4/micrometer-commons-1.13.4.jar:/Users/lrq/.m2/repository/org/hdrhistogram/HdrHistogram/2.2.2/HdrHistogram-2.2.2.jar:/Users/lrq/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/lrq/.m2/repository/com/knuddels/jtokkit/1.1.0/jtokkit-1.1.0.jar:/Users/lrq/.m2/repository/com/github/victools/jsonschema-generator/4.35.0/jsonschema-generator-4.35.0.jar:/Users/lrq/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/Users/lrq/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.14.2/jackson-core-2.14.2.jar:/Users/lrq/.m2/repository/com/github/victools/jsonschema-module-jackson/4.35.0/jsonschema-module-jackson-4.35.0.jar:/Users/lrq/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.16.1/jackson-databind-2.16.1.jar:/Users/lrq/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.16.1/jackson-annotations-2.16.1.jar:/Users/lrq/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.16.1/jackson-datatype-jsr310-2.16.1.jar:/Users/lrq/.m2/repository/org/apache/pdfbox/pdfbox/3.0.1/pdfbox-3.0.1.jar:/Users/lrq/.m2/repository/org/apache/pdfbox/pdfbox-io/3.0.1/pdfbox-io-3.0.1.jar:/Users/lrq/.m2/repository/org/apache/pdfbox/fontbox/3.0.1/fontbox-3.0.1.jar:/Users/lrq/.m2/repository/org/junit/jupiter/junit-jupiter/5.10.1/junit-jupiter-5.10.1.jar:/Users/lrq/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.10.1/junit-jupiter-api-5.10.1.jar:/Users/lrq/.m2/repository/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar:/Users/lrq/.m2/repository/org/junit/platform/junit-platform-commons/1.10.1/junit-platform-commons-1.10.1.jar:/Users/lrq/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/Users/lrq/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.10.1/junit-jupiter-params-5.10.1.jar:/Users/lrq/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.10.1/junit-jupiter-engine-5.10.1.jar:/Users/lrq/.m2/repository/org/junit/platform/junit-platform-engine/1.10.1/junit-platform-engine-1.10.1.jar:/Users/lrq/.m2/repository/org/springframework/ai/spring-ai-tika-document-reader/1.0.0-M3/spring-ai-tika-document-reader-1.0.0-M3.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-core/3.0.0-BETA2/tika-core-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/slf4j/slf4j-api/2.0.13/slf4j-api-2.0.13.jar:/Users/lrq/.m2/repository/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parsers-standard-package/3.0.0-BETA2/tika-parsers-standard-package-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-apple-module/3.0.0-BETA2/tika-parser-apple-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-zip-commons/3.0.0-BETA2/tika-parser-zip-commons-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/com/googlecode/plist/dd-plist/1.28/dd-plist-1.28.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-audiovideo-module/3.0.0-BETA2/tika-parser-audiovideo-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/com/drewnoakes/metadata-extractor/2.19.0/metadata-extractor-2.19.0.jar:/Users/lrq/.m2/repository/com/adobe/xmp/xmpcore/6.1.11/xmpcore-6.1.11.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-cad-module/3.0.0-BETA2/tika-parser-cad-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-code-module/3.0.0-BETA2/tika-parser-code-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/codelibs/jhighlight/1.1.0/jhighlight-1.1.0.jar:/Users/lrq/.m2/repository/org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar:/Users/lrq/.m2/repository/org/ow2/asm/asm/9.7/asm-9.7.jar:/Users/lrq/.m2/repository/com/epam/parso/2.0.14/parso-2.0.14.jar:/Users/lrq/.m2/repository/org/tallison/jmatio/1.5/jmatio-1.5.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-crypto-module/3.0.0-BETA2/tika-parser-crypto-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/bouncycastle/bcjmail-jdk18on/1.78.1/bcjmail-jdk18on-1.78.1.jar:/Users/lrq/.m2/repository/org/bouncycastle/bcutil-jdk18on/1.78.1/bcutil-jdk18on-1.78.1.jar:/Users/lrq/.m2/repository/org/bouncycastle/bcpkix-jdk18on/1.78.1/bcpkix-jdk18on-1.78.1.jar:/Users/lrq/.m2/repository/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-digest-commons/3.0.0-BETA2/tika-parser-digest-commons-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-font-module/3.0.0-BETA2/tika-parser-font-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-html-module/3.0.0-BETA2/tika-parser-html-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/jsoup/jsoup/1.18.1/jsoup-1.18.1.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-image-module/3.0.0-BETA2/tika-parser-image-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/com/github/jai-imageio/jai-imageio-core/1.4.0/jai-imageio-core-1.4.0.jar:/Users/lrq/.m2/repository/org/apache/pdfbox/jbig2-imageio/3.0.4/jbig2-imageio-3.0.4.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-mail-module/3.0.0-BETA2/tika-parser-mail-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-mail-commons/3.0.0-BETA2/tika-parser-mail-commons-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/james/apache-mime4j-core/0.8.11/apache-mime4j-core-0.8.11.jar:/Users/lrq/.m2/repository/org/apache/james/apache-mime4j-dom/0.8.11/apache-mime4j-dom-0.8.11.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-microsoft-module/3.0.0-BETA2/tika-parser-microsoft-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/com/pff/java-libpst/0.9.3/java-libpst-0.9.3.jar:/Users/lrq/.m2/repository/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar:/Users/lrq/.m2/repository/org/apache/poi/poi/5.3.0/poi-5.3.0.jar:/Users/lrq/.m2/repository/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar:/Users/lrq/.m2/repository/com/zaxxer/SparseBitSet/1.3/SparseBitSet-1.3.jar:/Users/lrq/.m2/repository/org/apache/poi/poi-scratchpad/5.3.0/poi-scratchpad-5.3.0.jar:/Users/lrq/.m2/repository/org/apache/poi/poi-ooxml/5.3.0/poi-ooxml-5.3.0.jar:/Users/lrq/.m2/repository/org/apache/poi/poi-ooxml-lite/5.3.0/poi-ooxml-lite-5.3.0.jar:/Users/lrq/.m2/repository/org/apache/xmlbeans/xmlbeans/5.2.1/xmlbeans-5.2.1.jar:/Users/lrq/.m2/repository/com/github/virtuald/curvesapi/1.08/curvesapi-1.08.jar:/Users/lrq/.m2/repository/commons-logging/commons-logging/1.3.3/commons-logging-1.3.3.jar:/Users/lrq/.m2/repository/com/healthmarketscience/jackcess/jackcess/4.0.7/jackcess-4.0.7.jar:/Users/lrq/.m2/repository/com/healthmarketscience/jackcess/jackcess-encrypt/4.0.2/jackcess-encrypt-4.0.2.jar:/Users/lrq/.m2/repository/org/slf4j/jcl-over-slf4j/2.0.13/jcl-over-slf4j-2.0.13.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-miscoffice-module/3.0.0-BETA2/tika-parser-miscoffice-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/commons/commons-collections4/4.5.0-M2/commons-collections4-4.5.0-M2.jar:/Users/lrq/.m2/repository/org/glassfish/jaxb/jaxb-runtime/4.0.5/jaxb-runtime-4.0.5.jar:/Users/lrq/.m2/repository/org/glassfish/jaxb/jaxb-core/4.0.5/jaxb-core-4.0.5.jar:/Users/lrq/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.2/jakarta.xml.bind-api-4.0.2.jar:/Users/lrq/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.3/jakarta.activation-api-2.1.3.jar:/Users/lrq/.m2/repository/org/eclipse/angus/angus-activation/2.0.2/angus-activation-2.0.2.jar:/Users/lrq/.m2/repository/org/glassfish/jaxb/txw2/4.0.5/txw2-4.0.5.jar:/Users/lrq/.m2/repository/com/sun/istack/istack-commons-runtime/4.1.2/istack-commons-runtime-4.1.2.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-news-module/3.0.0-BETA2/tika-parser-news-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/com/rometools/rome/2.1.0/rome-2.1.0.jar:/Users/lrq/.m2/repository/com/rometools/rome-utils/2.1.0/rome-utils-2.1.0.jar:/Users/lrq/.m2/repository/org/jdom/jdom2/2.0.6.1/jdom2-2.0.6.1.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-ocr-module/3.0.0-BETA2/tika-parser-ocr-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/commons/commons-exec/1.4.0/commons-exec-1.4.0.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-pdf-module/3.0.0-BETA2/tika-parser-pdf-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/pdfbox/pdfbox-tools/3.0.2/pdfbox-tools-3.0.2.jar:/Users/lrq/.m2/repository/info/picocli/picocli/4.7.5/picocli-4.7.5.jar:/Users/lrq/.m2/repository/org/apache/pdfbox/jempbox/1.8.17/jempbox-1.8.17.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-pkg-module/3.0.0-BETA2/tika-parser-pkg-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/tukaani/xz/1.9/xz-1.9.jar:/Users/lrq/.m2/repository/org/brotli/dec/0.1.2/dec-0.1.2.jar:/Users/lrq/.m2/repository/com/github/junrar/junrar/7.5.5/junrar-7.5.5.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-text-module/3.0.0-BETA2/tika-parser-text-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/com/github/albfernandez/juniversalchardet/2.5.0/juniversalchardet-2.5.0.jar:/Users/lrq/.m2/repository/org/apache/commons/commons-csv/1.11.0/commons-csv-1.11.0.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-webarchive-module/3.0.0-BETA2/tika-parser-webarchive-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/netpreserve/jwarc/0.30.0/jwarc-0.30.0.jar:/Users/lrq/.m2/repository/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-xml-module/3.0.0-BETA2/tika-parser-xml-module-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/tika/tika-parser-xmp-commons/3.0.0-BETA2/tika-parser-xmp-commons-3.0.0-BETA2.jar:/Users/lrq/.m2/repository/org/apache/pdfbox/xmpbox/3.0.2/xmpbox-3.0.2.jar:/Users/lrq/.m2/repository/org/gagravarr/vorbis-java-tika/0.8/vorbis-java-tika-0.8.jar:/Users/lrq/.m2/repository/org/gagravarr/vorbis-java-core/0.8/vorbis-java-core-0.8.jar file.split.MyKeywordEnRicher
Exception in thread "main" java.lang.AbstractMethodError: Method com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.getToolContext()Ljava/util/Map; is abstract
	at com.alibaba.cloud.ai.dashscope.chat.DashScopeChatOptions.getToolContext(DashScopeChatOptions.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)

my pom:

   <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud.ai</groupId>
            <artifactId>spring-ai-alibaba-starter</artifactId>
            <version>1.0.0-M2.1</version>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-pdf-document-reader</artifactId>
            <version>1.0.0-M3</version>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-tika-document-reader</artifactId>
            <version>1.0.0-M3</version>
        </dependency>

**Comment by lyqiangyuan** [comment]
I also encountered the same problem and later discovered that in spring-ai-alibaba-core-1.0-02.1. jar,  There is no getToolContext method in the com.alibaba.cloud.ai.dashscope.chat.DashScopeChatOptionsclass.

**Comment by yuluo-yx** [comment]
最近会发布一个新版本出来
